fix: deserialization flaw leading to unauthenticated remote code execution (#39)
## Overview
The project of `tiktok/tiktok-business-api-sdk` was used `com.fasterxml.jackson.core:jackson-databind` is a library which contains the general-purpose data-binding functionality and tree-model for Jackson Data Processor. Serialization is a process of converting an object into a sequence of bytes which can be persisted to a disk or database or can be sent through streams. The reverse process of creating objects from a sequence of bytes is called deserialization. Deserialization of untrusted data (CWE-502) occurs when an application deserializes untrusted data without sufficiently verifying that the resulting data will be valid, allowing the attacker to control the state or the flow of the execution.

```java
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.annotation.*;

class PolyWrapper {
    // In the original test code, @JsonTypeInfo annotation is added.
    // This allows recognition of additional class name information included in JSON without calling ObjectMapper.enableDefaultTyping().
    @JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.WRAPPER_ARRAY)
    public Object v;
}

// JSON with Object v field having class name as the first element and its content (scalar) as the second element in an array structure
String json = """
{
  "v" : [
    "java.util.logging.FileHandler",
    "/tmp/foobar.txt"
  ]
}
""";

mapper = new ObjectMapper();
try {
    def r = mapper.readValue(json, PolyWrapper.class);
} catch (com.fasterxml.jackson.databind.JsonMappingException e) {
    if (e.message.startsWith('Invalid type definition for type Ljava/util/logging/FileHandler;: Illegal type (java.util.logging.FileHandler) to deserialize: prevented for security reasons')) {
        // In version 2.8.10 with the fix, an exception occurs due to blacklisting of class names, and dangerous code is not executed.
        println 'your jackson version IS SAFE to CVE-2017-15095';
    } else {
        // In the unpatched version, instantiation occurs based on the class name.
        // It is possible to execute arbitrary code by specifying a getter with side effects in the field name, running gadgets, etc.
        // In this test case, it only reaches the point of attempting execution but fails, resulting in an exception indicating the failure.
        println 'your jackson version MAY NOT BE SAFE to CVE-2017-15095';
        println e.printStackTrace();
    }
}
```
```
your jackson version MAY NOT BE SAFE to CVE-2017-15095
com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of java.util.logging.FileHandler, problem: \tmp\foobar.txt.lck
 at [Source:
{
  "v" : [
    "java.util.logging.FileHandler",
    "/tmp/foobar.txt"
  ]
}
; line: 5, column: 5] (through reference chain: PolyWrapper["v"])
        at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:277)
(...)
Caused by: java.nio.file.NoSuchFileException: \tmp\foobar.txt.lck
(...)
        at java.util.logging.FileHandler.openFiles(FileHandler.java:459)
        at java.util.logging.FileHandler.<init>(FileHandler.java:292)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call1(AnnotatedConstructor.java:129)
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:318)
        ... 31 more
null
```
CVE-2017-15095
CWE-184
CWE-502
`CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H`